# Generated by Django 2.2.7 on 2020-01-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=500)),
                ('pages', models.CharField(max_length=10)),
                ('published_year', models.CharField(max_length=4)),
                ('isbn', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E', 'Educational'), ('F', 'Fiction'), ('N', 'Non-Fiction')], max_length=1)),
                ('image', models.ImageField(upload_to='book_images')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
