# Generated by Django 2.2.7 on 2020-02-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
