# Generated by Django 2.2.7 on 2020-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200203_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
